/* global instantsearch */

function app3() {
var phon_sample = "NT A FK KL P PL TS T TR TS RN HS TS NL AN AN 0 AR LK NS TS KS AL PT KL NS T KN XN NT AF FR A LS NX A NT FR FT AT PT KT TR AN KR AF NS NS TL AN SP ST N T 0 RJ RK SS AN KP TR AT RT TP TR RN KP AN FR RL TS ST T FS NS TR AS JS MK AP NS SN KR 0S T TR AS KN RT NL P NT AN PL FR P RT AN 0 NL TS RT MN AS AN P TL TP LK KR LM AF LK NR PT LT AR A TR P LS AT 0 T LS ST NN T RX 0 SP AN SP AN XN ST TR ST NT NK MR KN TR P AS LK TP NT KT NS TR NT HS P NT TS TL LT 0 MP HX H TK AL RF SK AS AS TT NT ST FT N KN TS NK FF AS TK NS A AT NK TR LK TS HS SS T 0R HF TR FN KS AS KM T AT PT A0 TS AF AK PL RF AS KR 0 HF LK TM RS XT LT AS A0 LT RT KS RF PP RN NS A SF NT AN TR A NK NK RL 0 AN NK LT LT RT P TR FL P TL RT AN HF AT LK 0 LS KR KN 0 AF SK AT NS TN T 0 0 T A NS HX K AN SF FF ST AN SR NS SL AF KN PS FF NK 0 PT T PP AR 0 TR KR 0M NS TR 0 NT 0T T KN K AF 0T FL AF MP T PN LN N 0R JS FR RF AS NT 0 0 AT PT TR ST S 0 SN JT P AP NS FR RL FN FR MK AN A RK P ST FR 0T 0 LN A0 T TR LK NT AN KP LS FL TL P PR LK 0T A KL XN FT 0 0 SF RP T TS KN AK TS A NN AT T AF SP FT T AF KL 0 SK TL 0M P AN ST JS T AF PR JS P KN A FR TL 0 0 N NT AF RJ AS A AF AT LK NJ ST HF AF 0R PN RS AS TF AR AT LK T 0 TS KS LK NS TF AN KN NS P 0T MT KT T KN NT 0 KL FR KS TN TS NJ H 0 NT AS A FR FR ST RS FK NS AS A H XN A0 TR KR T AN 0 TT A0 AX KT NK NS T KN KT A MR P MN SR LS NT RK 0 T JS AN AL AL PL 0 SF KN LK 0R KM TR 0 NS NS AF LS TM 0 HX NK SK 0 LK FF SN TS T KR P AL AF 0 0T AR T FR AT A A TM ST 0T MS PP T PL MR NS NT KT AL P AN FR PL KL TM ML A FR PT SL T 0R KN SR RF PR LS AL KP L0 MN TT RT ML AF 0 SN TR JN PT NS 0T PL T 0 AR SK T T KL AS AF FF 0T 0 T NK NS AS LK KN P AS TR FR LS PR XN TR AR A PL 0S A 0 KR A MK KN A ML 0 RT 0 NT NK MK AP PN FS AR P 0 AN SN PP NT AF TM ST T T P AF RF T AN T ST PR NT KS 0 AL AF 0 0 A0 KT 0 ST AN LK PN T LT AS KT LK SN LT A FN 0 PP AT A KP T T HS SX NS AR FR HX NT RK ST ST PL NK SN RF A 0 TM 0 T A A AF LK A PL AF RF 0S T AN FR KS NS 0 TN A TS AF TS A KP RF AS NS FL FL SS NS PT LT A AF K AF SP NS FR RT 0 0 0R AK AN TS AT A MK T NT AN AL AS AS X AN A NT AS KR LK H SP NT XT S T P A TR A SP FK TR P NT MN LK AT KS NS TT 0T A RT AN NT LT AN NK TS HF PL FR 0 0T T NL A HF 0 SM PT NT ST PT RT LM 0 0N AL NS KS 0T PR P RT LF NT LS 0 H SL P 0T A SX AN RT NS A NS KS RK A AF SS A PN SK T FS L 0 T AN XN L AL AS AF AN TL T A NS AR SS RT 0 KT A 0M XN RT RT NS P FN AT AF TL NK P KS LS RT NT H NK P FL PT KR NT NT AN AS 0 PL PL RK AS NT KN A AN AN P AS KP NJ MP XN KS FR AT AR AF 0M NT AF AS LS A PT SF A A NT KS AT RK A MR LS KR TS PN TP K A AF FL 0 AS RT AS AF RK RT 0 FN KS P JS PR NT A0 KR KT NS NN MR NX TR T H 0T AF P AT AL PL SP T T MK KN KN PR A0 A LK PT A TN 0S 0 LS HF RP 0R A A NT 0 H 0 TS SR NK P NS NT TL A NK A NM AS RM KR LK KN PT 0 KL 0 AF 0 MN NL TL FL 0 LK KR P AN PT FL TR 0M ST KN PL N FL KL RM 0 A KT FL KN NT A A0 T 0M 0 KS AS T XN NK NS RF FR 0T 0 FR TT H RF A ST MP TR LS KL TS RT 0 AR FN TM LK S 0 0T RK AF FL MP FL LK ST SL LT 0 TS RT MS TS A MN RT T RT ST ST NS KT LS AT T KN KN SP NT P AN HF AF AN PL MK T 0 AX AS NT PP 0 FR A T 0M 0 A KN HX ST ST AN KL A RT MR FR HF AN KS MN ST NS TT 0 NL MK PN NK AT T ST ST TS LK T NS LS RL A RK 0 PT TR HF NT RN NS KS P AN HX A 0 AF KS NT LT 0R LS TR XN T RK ST A 0 A 0 NN A RN TM 0 HX ST HF NS LK PL FR RF 0T H P T T TR ST NK 0 AL MR TS AL RT ST 0 AT 0R ST A AL AT AF 0N FL FL T LK TR AF NT PS A AR RK A 0 LK 0 NT AF AN 0 AS T PR HS AL FR AF FR 0 AF NS 0N TR 0 AN FR NT LK AL NT TS FS T AN AF RT AF AT LR FN AF XN TT A0 A0 SM LS 0T TR T PL KR AK 0 RF P KM KN FR AL KS 0N 0 KN N HX AT ST 0 0M NT AN 0 TN NT A A RT TS RF AN KN TK A SN RT RN RK AN RM AS 0S RT TS 0 NK ST AS T AN LK LT K P SN 0 NS K PL AL AN KS PR 0 AN TR FR KL 0R FS ST NS T TN KX FL TR AN KN TR AT 0N P A0 NL AN NK TT T ST NL 0 JS AS AN 0 P AN KN FF KR SP 0 0 TS AF FR AS NS LT RM FR MR H T RF NT AS LK TR ST 0S AP PL AR TS 0 SF RF 0S FF NT N T XN FR LF AF FL SN AP A KL NT KL NS AL TN A H RN NX LK LM 0 0 RS TR AN PL TL 0T SK NT LT TR 0 A FL 0 AF AS P LK TT NK KN AF HS PT AL H KL AR NK PT T XN 0 0 K AS XT TT T FR ST HX TN LK TR AT LS AR ST NT K TP TM A0 TS ST NT XS 0T PR SM 0 LK AS A P RM T RT P NS T RS SL SP XS P RT AS NS TS LN TM AN AL TS AN A TM LK AF PL NL HF RN NS 0 RT RK ST NS TR NN NT XN SF 0T AN AT NT SL KP ST SX NK FF ST KN 0 PS RT AF RT PL RM AL NS PS AR LN XN T A NK XN SS RT FR AN 0T AN RT TR MR P NX 0 T TR 0 T AL NT HF T SP XN AF FR 0 AS AP TR 0M 0R NK MK AF KR P SN A LK TS SN LN NK KN AS 0 KN TM A MT 0 NS T TT XN 0 RK K AL NT N NT XN ST NS KS NT A P AS SS ML TR T ST 0T RK RT RT FL A0 NK A RT HX SR 0 AS TR SK RM KM NT SN SF 0 NT NJ 0T NT AT AN KR AR T 0 NT SM FR AN FF S HX 0 FN RN RN AN AN A AN 0 KN AL ST KN NT LX SN NT 0 FL TR TM 0T 0 TN LT NT TP NK KS A N S RT XN AP P ST AF NL PT HS PL FT LS P P NT KL PT AF 0 LT JS NT AR KN 0 PS AK KT NT TS P TS KS PS NK AT SF RM TN T TR ST NT NR P T AS XN PR P 0 TM RL AF 0T RS AF XN 0 P N FL TR TT TK AN TR 0T AN TN AS P A A TP A0 TR AK T PP TF A0 0 KP NS AF AF AT NK T 0T NS AR P 0 TM A ST TR LT HS 0 AP NT KP MR SP AK T ST KN AN SS NT PT KR 0 ST 0 FS A NL TS RT 0R AS 0 P TT TX AF A LK AL AT NT H RJ AR KN KX KN RT T TS AF 0 MN P AR AS RT 0T LK LR TT 0 AN PN ST 0 KR TR NT AF 0 A NS FF RM RT A T NT LF 0 0 A MT A ST A AS LT FS TT FR SN FR LR KN FS KN T RT AL NJ MS H NK TL FL HF 0 0 A SS T AL 0N PL 0N 0R LP 0 T FF SX AL RK PT SR N NK PK KR 0T NT RT 0 A HF NT ST 0 AL TM AN SN NT AS MK NL NT NK AT AN AF KM HS 0 X T AS AF 0 LS PL T RJ PL NT NT 0 AN NS NK 0T 0 AS SX 0T NT A TR AS T";
var phone_samp_split = phon_sample.split(" ");
var random_index = Math.floor(Math.random() * (phone_samp_split.length));
choice_query2 = phone_samp_split[random_index];

  var search3 = instantsearch({
    appId: 'YOUR ALGOLIA APP ID',
    apiKey: 'YOUR ALGOLIA API KEY',
    indexName: 'YOUR ALGOLIA INDEX NAME'
    searchParameters: {
    	"query": choice_query2
    }
});

  var widgets = [
    instantsearch.widgets.hits({
      container: '#hits2',
      templates: {
      empty: 'No results',
      item: '<h3 class="line3">{{{line}}}</h3>'	
// 	  item: getTemplate('hit')
    },
    hitsPerPage: 4
    })
  ];

  widgets.forEach(search3.addWidget, search3);
  search3.start();
}

function getTemplate(templateName) {
  return document.querySelector('#' + templateName + '-template').innerHTML;
}

function getHeader(title) {
  return '<h5>' + title + '</h5>';
}
